# Generated by Django 5.1.1 on 2024-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitars',
            name='product_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
