# Generated by Django 5.1.1 on 2024-10-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chathistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='owner',
            new_name='name',
        ),
    ]
