# Generated by Django 5.1.1 on 2024-10-05 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_owner_chathistory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anser', models.CharField(blank=True, max_length=1000)),
                ('save_date', models.DateField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chathistory')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
